swagger: '2.0'
info:
  title: Account and Transaction API Specification
  description: Swagger for Account and Transaction API Specification
  termsOfService: https://www.openbanking.org.uk/terms
  contact:
    name: Service Desk
    url: >-
      https://rbsgroupapiservicedesk.spectrumhosting.net/plugins/servlet/desk/portal/1
  license:
    name: open-licence
    url: https://www.openbanking.org.uk/open-licence
  version: v3.1.10
basePath: /open-banking/v3.1/aisp
host: api.natwest.com
schemes:
  - https
paths:
  /account-access-consents:
    post:
      tags:
        - Account Access
      summary: Create an account access consent
      description: Create an account access consent
      operationId: CreateAccountAccessConsent
      security:
        - TPPOAuth2Security:
            - tpp_client_credential
  /account-access-consents/{ConsentId}:
    get:
      tags:
        - Account Access
      summary: Get an account access consent
      description: Get an account access consent
      operationId: GetAccountAccessConsent
      security:
        - TPPOAuth2Security:
            - tpp_client_credential
    delete:
      tags:
        - Account Access
      summary: Delete an account access consent
      description: Delete an account access consent
      operationId: DeleteAccountAccessConsent
      security:
        - TPPOAuth2Security:
            - tpp_client_credential
  /accounts:
    get:
      tags:
        - Accounts
      summary: Get Accounts
      description: Get a list of accounts
      operationId: GetAccounts
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}:
    get:
      tags:
        - Accounts
      summary: Get Account
      description: Get an account
      operationId: GetAccount
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/transactions:
    get:
      tags:
        - Accounts
      summary: Get Account Transactions
      description: >-
        Get transactions related to an account. See the [Transactions Endpoint
        section](https://www.bankofapis.com/products/natwest-group-open-banking/accounts/documentation/nwb/3.1.10#transactions-endpoint)
        for more detail on how fields in the request affect the transaction data
        in the response.
      operationId: GetAccountTransactions
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/statements:
    get:
      tags:
        - Accounts
      summary: Get Account Statements
      description: >-
        Get statements related to an account. See the [Statements Endpoint
        section](https://www.bankofapis.com/products/accounts/documentation/nwb/3.1.6#Statements-endpoint)
        for more detail.
      operationId: GetAccountStatements
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/beneficiaries:
    get:
      tags:
        - Accounts
      summary: Get Account Beneficiaries
      description: Get Beneficiaries related to an account
      operationId: GetAccountBeneficiaries
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/balances:
    get:
      tags:
        - Accounts
      summary: Get Account Balances
      description: Get Balances related to an account
      operationId: GetAccountBalances
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/direct-debits:
    get:
      tags:
        - Accounts
      summary: Get Account Direct Debits
      description: Get Direct Debits related to an account
      operationId: GetAccountDirectDebits
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/standing-orders:
    get:
      tags:
        - Accounts
      summary: Get Account Standing Orders
      description: Get Standing Orders related to an account
      operationId: GetAccountStandingOrders
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/product:
    get:
      tags:
        - Accounts
      summary: Get Account Product
      description: Get Product related to an account
      operationId: GetAccountProduct
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/scheduled-payments:
    get:
      tags:
        - Accounts
      summary: Get Account Scheduled Payments
      description: Get Scheduled Payments related to an account
      operationId: GetAccountScheduledPayments
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/offers:
    get:
      tags:
        - Accounts
      summary: Get Account Offer
      description: Get Offer related to an account
      operationId: GetAccountOffer
      security:
        - PSUOAuth2Security:
            - accounts
  /accounts/{AccountId}/card-holder-names:
    get:
      '400':
        description: Bad Request
        schema:
          title: Bad Request
          description: An array of detail error codes and messages.
          type: object
          properties:
            Code:
              description: High level textual error code, to help categorize the errors.
              type: string
              minLength: 1
              maxLength: 40
            Message:
              description: >-
                Brief Error message, e.g., 'There is something wrong with the
                request parameters provided'
              type: string
              minLength: 1
              maxLength: 500
            Errors:
              title: Errors
              description: Errors
              type: array
              items:
                title: Error
                description: Error
                type: object
                properties:
                  ErrorCode:
                    description: Low level textual error code, e.g., UK.OBIE.Field.Missing
                    type: string
                    minLength: 1
                    maxLength: 128
                  Message:
                    description: >-
                      A description of the error that occurred. e.g., 'A
                      mandatory field isn't supplied'
                    type: string
                    minLength: 1
                    maxLength: 500
                required:
                  - ErrorCode
                  - Message
                additionalProperties: false
                minProperties: 1
              minItems: 1
          required:
            - Code
            - Message
            - Errors
      '401':
        description: Unauthorized
      '403':
        description: Forbidden
      '405':
        description: Method Not Allowed
      '406':
        description: Not Acceptable
      '429':
        description: Too Many Requests
      '500':
        description: Internal Server Error
        schema:
          title: Internal Server Error
          description: An array of detail error codes and messages.
          type: object
          properties:
            Code:
              description: High level textual error code, to help categorize the errors.
              type: string
              minLength: 1
              maxLength: 40
            Message:
              description: >-
                Brief Error message, e.g., 'There is something wrong with the
                request parameters provided'
              type: string
              minLength: 1
              maxLength: 500
            Errors:
              title: Errors
              description: Errors
              type: array
              items:
                title: Error
                description: Error
                type: object
                properties:
                  ErrorCode:
                    description: Low level textual error code, e.g., UK.OBIE.Field.Missing
                    type: string
                    minLength: 1
                    maxLength: 128
                  Message:
                    description: >-
                      A description of the error that occurred. e.g., 'A
                      mandatory field isn't supplied'
                    type: string
                    minLength: 1
                    maxLength: 500
                required:
                  - ErrorCode
                  - Message
                additionalProperties: false
                minProperties: 1
              minItems: 1
          required:
            - Code
            - Message
            - Errors
      tags:
        - Accounts
      summary: card-holder-names
      description: >-
        Cards API is  related to an account. See the [card holder names Endpoint
        section](https://www.bankofapis.com/products/accounts/documentation/nwb/3.1.10#card-holder-names)
        for more detail.
      operationId: card-holder-names
      security:
        - PSUOAuth2Security:
            - accounts
securityDefinitions:
  PSUOAuth2Security:
    type: oauth2
    flow: accessCode
    tokenUrl: https://secure1t.natwest.com/as/token.oauth2
    authorizationUrl: https://secure1.natwest.com/as/authorization.oauth2
    scopes:
      accounts: Ability to read Accounts information
    description: >-
      OAuth flow, it is required when the PSU needs to perform SCA with the
      ASPSP when a TPP wants to access an ASPSP resource owned by the PSU
  TPPOAuth2Security:
    type: oauth2
    flow: application
    tokenUrl: https://secure1t.natwest.com/as/token.oauth2
    scopes:
      tpp_client_credential: TPP Client Credential Scope
    description: TPP client credential authorisation flow with the ASPSP