@wellKnownEndpoint = {{$dotenv WELL_KNOW_ENDPOINT}}
@apiUrlPrefix = {{$dotenv API_URL_PREFIX}}
@redirectUrl = {{$dotenv REDIRECT_URL}}
@psuUsername = {{$dotenv PSU_USER_NAME}}
@clientId = {{$dotenv CLIENT_ID}}
@clientSecret = {{$dotenv CLIENT_SECRET}}

### Retrieve well known endpoint


# @name retrieveWellKnownEndpoint

curl -k -X GET \
  {{wellKnownEndpoint}}

### Retrieve Access Token for Account Request

@tokenEndpoint = {{retrieveWellKnownEndpoint.response.body.token_endpoint}}
@authorizationEndpoint = {{retrieveWellKnownEndpoint.response.body.authorization_endpoint}}
@grant_type = client_credentials
@scope = accounts

# @name retrieveAccessToken

curl -k -X POST \
  {{tokenEndpoint}} \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'grant_type={{grant_type}}&client_id={{clientId}}&client_secret={{clientSecret}}&scope={{scope}}'


### Post Account request

@accountRequestAccessToken = {{retrieveAccessToken.response.body.access_token}}

# @name postAccountRequest

curl -k -X POST \
  {{apiUrlPrefix}}/open-banking/v3.1/aisp/account-access-consents \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {{accountRequestAccessToken}}' \
  -d '{
  "Data": {
    "Permissions": [
      "ReadAccountsDetail",
      "ReadBalances",
      "ReadTransactionsCredits",
      "ReadTransactionsDebits",
      "ReadTransactionsDetail"
    ]
  },
  "Risk": {}
}'

### Approve Consent programmatically

@accountConsentId = {{postAccountRequest.response.body.Data.ConsentId}};
@encodedRedirectUrl = {{redirectUrl}}

curl -k -X GET \
  {{authorizationEndpoint}}?client_id={{clientId}}&response_type=code id_token&scope=openid accounts&redirect_uri={{encodedRedirectUrl}}&state=ABC&request={{accountConsentId}}&authorization_mode=AUTO_POSTMAN&authorization_username={{psuUsername}}